-- Quistock - updated PostgreSQL schema
-- Applied changes:
-- Canonical PostgreSQL schema for the QuiStock API.
-- ERP product codes are also used as SKUs and must fit VARCHAR(100).
-- ERP batches require expiration date, sale price and unit cost.
-- Product and branch metrics are stored in product_store.
-- User passwords stay in SQL; NoSQL auth stores sessions and refresh tokens only.

CREATE TYPE "store_status" AS ENUM (
  'ACTIVE',
  'INACTIVE'
);

CREATE TYPE "user_status" AS ENUM (
  'ACTIVE',
  'INACTIVE'
);

CREATE TYPE "flow_type" AS ENUM (
  'HIGH',
  'MEDIUM',
  'LOW'
);

CREATE TYPE "suggestion_type" AS ENUM (
  'ORDER',
  'PROMOTION',
  'MONITOR'
);

CREATE TYPE "suggestion_origin" AS ENUM (
  'ML',
  'EMPLOYEE',
  'MANAGER'
);

CREATE TYPE "suggestion_status" AS ENUM (
  'GENERATED',
  'IN_EMPLOYEE_TRIAGE',
  'SENT_TO_MANAGER',
  'APPROVED',
  'REJECTED'
);

CREATE TYPE "triage_action" AS ENUM (
  'EDIT',
  'FORWARD'
);

CREATE TYPE "decision_type" AS ENUM (
  'APPROVE',
  'REJECT'
);

CREATE TYPE "suggestion_log_event" AS ENUM (
  'GENERATED',
  'EDITED',
  'FORWARDED',
  'APPROVED',
  'REJECTED',
  'EXPIRED'
);

CREATE TYPE "erp_sync_status" AS ENUM (
  'STARTED',
  'COMPLETED',
  'COMPLETED_WITH_ERRORS',
  'FAILED'
);

CREATE TYPE "ml_execution_status" AS ENUM (
  'STARTED',
  'COMPLETED',
  'COMPLETED_WITH_ERRORS',
  'FAILED'
);

CREATE TABLE "user_account" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" BIGINT NOT NULL,
  "name" VARCHAR(150) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password_hash" VARCHAR(255) NOT NULL,
  "profile_photo_url" VARCHAR(500),
  "status" user_status NOT NULL DEFAULT 'ACTIVE',
  "created_by_id" BIGINT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "role" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" VARCHAR(50) UNIQUE NOT NULL,
  "name" VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE "region_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" VARCHAR(50) UNIQUE NOT NULL,
  "name" VARCHAR(100) UNIQUE NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "permission" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" VARCHAR(100) UNIQUE NOT NULL,
  "name" VARCHAR(150) NOT NULL,
  "description" TEXT
);

CREATE TABLE "role_permission" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" BIGINT NOT NULL,
  "permission_id" BIGINT NOT NULL
);

CREATE TABLE "user_store" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "store_id" BIGINT NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "assigned_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "unassigned_at" TIMESTAMPTZ,
  CONSTRAINT "chk_user_store_dates"
    CHECK (unassigned_at IS NULL OR unassigned_at >= assigned_at),
  CONSTRAINT "chk_user_store_active_state"
    CHECK (
      (active = TRUE AND unassigned_at IS NULL)
      OR
      (active = FALSE AND unassigned_at IS NOT NULL)
  )
);

CREATE TABLE "region_manager_assignment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "region_id" BIGINT NOT NULL,
  "user_id" BIGINT NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "erp_sync" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "started_at" TIMESTAMPTZ NOT NULL,
  "finished_at" TIMESTAMPTZ,
  "status" erp_sync_status NOT NULL,
  "records_read" INT,
  "records_inserted" INT,
  "records_updated" INT,
  "records_deactivated" INT,
  "error_message" TEXT,
  CONSTRAINT "chk_erp_sync_counts"
    CHECK (
      (records_read IS NULL OR records_read >= 0)
      AND (records_inserted IS NULL OR records_inserted >= 0)
      AND (records_updated IS NULL OR records_updated >= 0)
      AND (records_deactivated IS NULL OR records_deactivated >= 0)
    ),
  CONSTRAINT "chk_erp_sync_dates"
    CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE "store" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "erp_id" VARCHAR(150) UNIQUE NOT NULL,
  "name" VARCHAR(150) NOT NULL,
  "region_id" BIGINT,
  "status" store_status NOT NULL DEFAULT 'ACTIVE',
  "created_by_id" BIGINT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deactivated_at" TIMESTAMPTZ,
  "last_sync_id" BIGINT
);

CREATE TABLE "store_address" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" BIGINT UNIQUE NOT NULL,
  "postal_code" VARCHAR(20),
  "street" VARCHAR(200),
  "number" VARCHAR(30),
  "complement" VARCHAR(100),
  "neighborhood" VARCHAR(100),
  "city" VARCHAR(100),
  "state" VARCHAR(100)
);

CREATE TABLE "category" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "erp_id" VARCHAR(150) UNIQUE NOT NULL,
  "name" VARCHAR(150) NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "last_sync_id" BIGINT
);

CREATE TABLE "product" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "erp_id" VARCHAR(150) UNIQUE NOT NULL,
  "sku" VARCHAR(100) UNIQUE NOT NULL,
  "category_id" BIGINT,
  "name" VARCHAR(200) NOT NULL,
  "sale_price" NUMERIC(12,2) NOT NULL,
  "minimum_stock_quantity" NUMERIC(14,3),
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "last_sync_id" BIGINT,
  CONSTRAINT "chk_product_sale_price"
    CHECK (sale_price >= 0),
  CONSTRAINT "chk_product_minimum_stock_quantity"
    CHECK (
      minimum_stock_quantity IS NULL
      OR minimum_stock_quantity >= 0
    )
);

CREATE TABLE "batch" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "erp_id" VARCHAR(150) UNIQUE NOT NULL,
  "batch_number" VARCHAR(150) NOT NULL,
  "product_id" BIGINT NOT NULL,
  "store_id" BIGINT NOT NULL,
  "expiration_date" DATE NOT NULL,
  "entry_date" TIMESTAMPTZ,
  "sale_price" NUMERIC(12,2) NOT NULL,
  "unit_cost" NUMERIC(12,2) NOT NULL,
  "current_balance" NUMERIC(14,3) NOT NULL,
  "quality_certificate" TEXT,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "last_sync_id" BIGINT,
  CONSTRAINT "chk_batch_current_balance"
    CHECK (current_balance >= 0),
  CONSTRAINT "chk_batch_prices"
    CHECK (
      sale_price >= 0
      AND unit_cost >= 0
    )
);

-- Projeção dos valores fornecidos pelo ERP por produto e filial. O endpoint
-- atual fornece vendas agregadas, não eventos individuais de venda.
CREATE TABLE "product_store" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" BIGINT NOT NULL,
  "store_id" BIGINT NOT NULL,
  "minimum_stock_quantity" NUMERIC(14,3),
  "supplier_lead_time_days" INT,
  "sales_7d" NUMERIC(14,3) NOT NULL DEFAULT 0,
  "sales_30d" NUMERIC(14,3) NOT NULL DEFAULT 0,
  "sale_price" NUMERIC(12,2) NOT NULL,
  "unit_cost" NUMERIC(12,2) NOT NULL,
  "last_restock_at" TIMESTAMPTZ,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "last_sync_id" BIGINT,
  CONSTRAINT "chk_product_store_minimum_stock"
    CHECK (minimum_stock_quantity IS NULL OR minimum_stock_quantity >= 0),
  CONSTRAINT "chk_product_store_lead_time"
    CHECK (supplier_lead_time_days IS NULL OR supplier_lead_time_days >= 0),
  CONSTRAINT "chk_product_store_sales"
    CHECK (sales_7d >= 0 AND sales_30d >= 0),
  CONSTRAINT "chk_product_store_prices"
    CHECK (
      sale_price >= 0
      AND unit_cost >= 0
    )
);

CREATE TABLE "sale" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "erp_id" VARCHAR(150) UNIQUE NOT NULL,
  "store_id" BIGINT NOT NULL,
  "sale_date" TIMESTAMPTZ NOT NULL,
  "last_sync_id" BIGINT
);

CREATE TABLE "sale_item" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sale_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "batch_id" BIGINT NOT NULL,
  "quantity" NUMERIC(14,3) NOT NULL,
  "total_amount" NUMERIC(12,2) NOT NULL,
  "erp_id" VARCHAR(150),
  "last_sync_id" BIGINT,
  CONSTRAINT "chk_sale_item_quantity"
    CHECK (quantity > 0),
  CONSTRAINT "chk_sale_item_total_amount"
    CHECK (total_amount >= 0)
);

CREATE TABLE "inventory_movement" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "erp_id" VARCHAR(150) UNIQUE NOT NULL,
  "store_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "batch_id" BIGINT NOT NULL,
  "movement_type" VARCHAR(80) NOT NULL,
  "quantity" NUMERIC(14,3) NOT NULL,
  "balance_after" NUMERIC(14,3),
  "movement_date" TIMESTAMPTZ NOT NULL,
  "sale_item_id" BIGINT,
  "last_sync_id" BIGINT,
  CONSTRAINT "chk_inventory_movement_quantity"
    CHECK (quantity > 0),
  CONSTRAINT "chk_inventory_movement_balance"
    CHECK (balance_after IS NULL OR balance_after >= 0)
);

CREATE TABLE "ml_execution" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_version" VARCHAR(100) NOT NULL,
  "execution_date" TIMESTAMPTZ NOT NULL,
  "cutoff_date" DATE NOT NULL,
  "window_start_date" DATE NOT NULL,
  "window_end_date" DATE NOT NULL,
  "status" ml_execution_status NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_ml_execution_window"
    CHECK (window_end_date >= window_start_date)
);

CREATE TABLE "flow_type_catalog" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" flow_type UNIQUE NOT NULL,
  "description" VARCHAR(100) NOT NULL
);

CREATE TABLE "product_analysis" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ml_execution_id" BIGINT,
  "store_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "flow_type_id" BIGINT NOT NULL,
  "metrics" JSONB NOT NULL,
  "context" JSONB,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "suggestion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_analysis_id" BIGINT,
  "store_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "type" suggestion_type NOT NULL,
  "origin" suggestion_origin NOT NULL,
  "status" suggestion_status NOT NULL,
  "ml_batch_count" INT,
  "current_batch_count" INT,
  "ml_discount_percentage" NUMERIC(5,2),
  "current_discount_percentage" NUMERIC(5,2),
  "promotion_valid_from" DATE,
  "promotion_valid_until" DATE,
  "reference_sale_price" NUMERIC(12,2),
  "promotional_price" NUMERIC(12,2),
  "available_for_triage" BOOLEAN NOT NULL DEFAULT TRUE,
  "created_by_id" BIGINT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ,
  CONSTRAINT "chk_suggestion_batch_counts"
    CHECK (
      (ml_batch_count IS NULL OR ml_batch_count > 0)
      AND (current_batch_count IS NULL OR current_batch_count > 0)
    ),
  CONSTRAINT "chk_suggestion_discounts"
    CHECK (
      (ml_discount_percentage IS NULL OR ml_discount_percentage >= 0 AND ml_discount_percentage <= 100)
      AND (current_discount_percentage IS NULL OR current_discount_percentage >= 0 AND current_discount_percentage <= 100)
    ),
  CONSTRAINT "chk_suggestion_prices"
    CHECK (
      (reference_sale_price IS NULL OR reference_sale_price >= 0)
      AND (promotional_price IS NULL OR promotional_price >= 0)
    ),
  CONSTRAINT "chk_suggestion_type_fields"
    CHECK (
      (
        type = 'ORDER'
        AND ml_discount_percentage IS NULL
        AND current_discount_percentage IS NULL
        AND promotion_valid_from IS NULL
        AND promotion_valid_until IS NULL
        AND reference_sale_price IS NULL
        AND promotional_price IS NULL
      )
      OR
      (
        type = 'PROMOTION'
        AND promotion_valid_from IS NOT NULL
        AND promotion_valid_until IS NOT NULL
        AND promotion_valid_until >= promotion_valid_from
      )
      OR
      (
        type = 'MONITOR'
        AND product_analysis_id IS NOT NULL
        AND origin = 'ML'
        AND status = 'GENERATED'
        AND ml_batch_count IS NULL
        AND current_batch_count IS NULL
        AND ml_discount_percentage IS NULL
        AND current_discount_percentage IS NULL
        AND promotion_valid_from IS NULL
        AND promotion_valid_until IS NULL
        AND reference_sale_price IS NULL
        AND promotional_price IS NULL
        AND available_for_triage = FALSE
      )
    ),
  CONSTRAINT "chk_suggestion_origin_creator"
    CHECK (
      (origin = 'ML' AND created_by_id IS NULL)
      OR
      origin IN ('EMPLOYEE', 'MANAGER')
    )
);

CREATE TABLE "suggestion_triage" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "suggestion_id" BIGINT UNIQUE NOT NULL,
  "employee_id" BIGINT,
  "last_action" triage_action NOT NULL,
  "forwarded_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "suggestion_decision" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "suggestion_id" BIGINT UNIQUE NOT NULL,
  "manager_id" BIGINT,
  "decision" decision_type NOT NULL,
  "final_batch_count" INT,
  "final_discount_percentage" NUMERIC(5,2),
  "final_promotional_price" NUMERIC(12,2),
  "final_promotion_valid_from" DATE,
  "final_promotion_valid_until" DATE,
  "justification" TEXT,
  "decided_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_decision_batch_count"
    CHECK (final_batch_count IS NULL OR final_batch_count > 0),
  CONSTRAINT "chk_decision_discount"
    CHECK (
      final_discount_percentage IS NULL
      OR (final_discount_percentage >= 0 AND final_discount_percentage <= 100)
    ),
  CONSTRAINT "chk_decision_price"
    CHECK (final_promotional_price IS NULL OR final_promotional_price >= 0),
  CONSTRAINT "chk_decision_promotion_validity"
    CHECK (
      (final_promotion_valid_from IS NULL AND final_promotion_valid_until IS NULL)
      OR
      (
        final_promotion_valid_from IS NOT NULL
        AND final_promotion_valid_until IS NOT NULL
        AND final_promotion_valid_until >= final_promotion_valid_from
      )
    ),
  CONSTRAINT "chk_decision_justification"
    CHECK (
      decision <> 'REJECT'
      OR (justification IS NOT NULL AND BTRIM(justification) <> '')
    )
);

CREATE TABLE "suggestion_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "suggestion_id" BIGINT NOT NULL,
  "user_id" BIGINT,
  "event" suggestion_log_event NOT NULL,
  "recorded_status" VARCHAR(60),
  "batch_quantity" INT,
  "discount_percentage" NUMERIC(5,2),
  "promotional_price" NUMERIC(12,2),
  "valid_from" DATE,
  "valid_until" DATE,
  "previous_data" JSONB,
  "new_data" JSONB,
  "reason" TEXT,
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "chk_suggestion_log_batch_quantity"
    CHECK (batch_quantity IS NULL OR batch_quantity > 0),
  CONSTRAINT "chk_suggestion_log_discount"
    CHECK (
      discount_percentage IS NULL
      OR (discount_percentage >= 0 AND discount_percentage <= 100)
    ),
  CONSTRAINT "chk_suggestion_log_price"
    CHECK (promotional_price IS NULL OR promotional_price >= 0),
  CONSTRAINT "chk_suggestion_log_validity"
    CHECK (
      (valid_from IS NULL AND valid_until IS NULL)
      OR
      (
        valid_from IS NOT NULL
        AND valid_until IS NOT NULL
        AND valid_until >= valid_from
      )
    )
);

CREATE TABLE "audit_event" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT,
  "entity" VARCHAR(80) NOT NULL,
  "entity_id" BIGINT NOT NULL,
  "action" VARCHAR(80) NOT NULL,
  "data" JSONB,
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Auditoria completa de alterações nas tabelas transacionais selecionadas.
-- O campo data preserva NEW, OLD, TG_OP e CURRENT_USER sem alterar o modelo
-- de negócio das entidades auditadas.
CREATE OR REPLACE FUNCTION "capture_audit_event"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_entity_id BIGINT;
  v_user_id BIGINT;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_entity_id := OLD.id;
  ELSE
    v_entity_id := NEW.id;
  END IF;

  IF TG_TABLE_NAME = 'suggestion' THEN
    IF TG_OP = 'DELETE' THEN
      v_user_id := OLD.created_by_id;
    ELSE
      v_user_id := NEW.created_by_id;
    END IF;
  ELSIF TG_TABLE_NAME = 'suggestion_decision' THEN
    IF TG_OP = 'DELETE' THEN
      v_user_id := OLD.manager_id;
    ELSE
      v_user_id := NEW.manager_id;
    END IF;
  END IF;

  INSERT INTO "audit_event" (
    "user_id",
    "entity",
    "entity_id",
    "action",
    "data",
    "occurred_at"
  )
  VALUES (
    v_user_id,
    TG_TABLE_NAME,
    v_entity_id,
    TG_OP,
    jsonb_build_object(
      'NEW', CASE
        WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW)
        ELSE NULL
      END,
      'OLD', CASE
        WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD)
        ELSE NULL
      END,
      'TG_OP', TG_OP,
      'CURRENT_USER', CURRENT_USER
    ),
    CURRENT_TIMESTAMP
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "trg_suggestion_audit"
  ON "suggestion";

CREATE TRIGGER "trg_suggestion_audit"
AFTER INSERT OR UPDATE OR DELETE
ON "suggestion"
FOR EACH ROW
EXECUTE FUNCTION "capture_audit_event"();

DROP TRIGGER IF EXISTS "trg_suggestion_decision_audit"
  ON "suggestion_decision";

CREATE TRIGGER "trg_suggestion_decision_audit"
AFTER INSERT OR UPDATE OR DELETE
ON "suggestion_decision"
FOR EACH ROW
EXECUTE FUNCTION "capture_audit_event"();

CREATE UNIQUE INDEX "uq_role_permission_pair"
  ON "role_permission" ("role_id", "permission_id");

CREATE UNIQUE INDEX "uq_user_store_active_pair"
  ON "user_store" ("user_id", "store_id")
  WHERE "active" = TRUE;

CREATE UNIQUE INDEX "uq_user_store_one_active_per_user"
  ON "user_store" ("user_id")
  WHERE "active" = TRUE;

CREATE UNIQUE INDEX "uq_user_account_email_normalized"
  ON "user_account" (LOWER(BTRIM("email")));

CREATE UNIQUE INDEX "uq_region_manager_active_region"
  ON "region_manager_assignment" ("region_id")
  WHERE "active" = TRUE;

CREATE UNIQUE INDEX "uq_region_manager_active_user"
  ON "region_manager_assignment" ("user_id")
  WHERE "active" = TRUE;

CREATE INDEX "idx_user_store_user_active"
  ON "user_store" ("user_id", "active");

CREATE INDEX "idx_user_store_store_active"
  ON "user_store" ("store_id", "active");

CREATE INDEX "idx_sale_item_sale_product_batch"
  ON "sale_item" ("sale_id", "product_id", "batch_id");

CREATE UNIQUE INDEX "uq_product_analysis_execution_store_product"
  ON "product_analysis" ("ml_execution_id", "store_id", "product_id");

CREATE UNIQUE INDEX "uq_suggestion_product_analysis"
  ON "suggestion" ("product_analysis_id")
  WHERE "product_analysis_id" IS NOT NULL;

CREATE INDEX "idx_suggestion_log_suggestion_occurred"
  ON "suggestion_log" ("suggestion_id", "occurred_at");

CREATE INDEX "idx_audit_event_entity"
  ON "audit_event" ("entity", "entity_id");

CREATE UNIQUE INDEX "uq_product_store_pair"
  ON "product_store" ("product_id", "store_id");

CREATE INDEX "idx_product_store_store_active"
  ON "product_store" ("store_id", "active");

CREATE INDEX "idx_batch_product_store_active"
  ON "batch" ("product_id", "store_id", "active");

COMMENT ON COLUMN "inventory_movement"."movement_type"
  IS 'Type defined by the ERP. Examples: receipt, sale, loss, or adjustment.';

COMMENT ON COLUMN "product"."minimum_stock_quantity"
  IS 'Minimum stock quantity provided by the ERP for the product.';

COMMENT ON COLUMN "product_store"."minimum_stock_quantity"
  IS 'ERP minimum stock quantity for this product at this store.';

COMMENT ON COLUMN "product_store"."supplier_lead_time_days"
  IS 'Supplier delivery lead time in days provided by the ERP for this product at this store.';

COMMENT ON COLUMN "product_store"."unit_cost"
  IS 'Unit acquisition cost provided by the ERP for the latest batch at this store.';

COMMENT ON COLUMN "product_store"."last_restock_at"
  IS 'Entry date of the most recently received batch provided by the ERP.';

COMMENT ON COLUMN "suggestion"."promotion_valid_from"
  IS 'Start date of the suggested promotion validity period.';

COMMENT ON COLUMN "suggestion"."promotion_valid_until"
  IS 'End date of the suggested promotion validity period.';

COMMENT ON COLUMN "suggestion_decision"."final_promotion_valid_from"
  IS 'Start date of the promotion validity period decided by the manager.';

COMMENT ON COLUMN "suggestion_decision"."final_promotion_valid_until"
  IS 'End date of the promotion validity period decided by the manager.';

COMMENT ON COLUMN "product_analysis"."metrics"
  IS 'Temporary format while the ML metrics contract is not finalized.';

COMMENT ON COLUMN "suggestion_decision"."justification"
  IS 'Required when decision = REJECT.';

ALTER TABLE "user_account"
  ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_account"
  ADD FOREIGN KEY ("created_by_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permission"
  ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permission"
  ADD FOREIGN KEY ("permission_id") REFERENCES "permission" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_store"
  ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_store"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "region_manager_assignment"
  ADD FOREIGN KEY ("region_id") REFERENCES "region_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "region_manager_assignment"
  ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "store"
  ADD FOREIGN KEY ("created_by_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "store"
  ADD FOREIGN KEY ("region_id") REFERENCES "region_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "store"
  ADD FOREIGN KEY ("last_sync_id") REFERENCES "erp_sync" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "store_address"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "category"
  ADD FOREIGN KEY ("last_sync_id") REFERENCES "erp_sync" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product"
  ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product"
  ADD FOREIGN KEY ("last_sync_id") REFERENCES "erp_sync" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batch"
  ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batch"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "batch"
  ADD FOREIGN KEY ("last_sync_id") REFERENCES "erp_sync" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_store"
  ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_store"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_store"
  ADD FOREIGN KEY ("last_sync_id") REFERENCES "erp_sync" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale"
  ADD FOREIGN KEY ("last_sync_id") REFERENCES "erp_sync" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_item"
  ADD FOREIGN KEY ("sale_id") REFERENCES "sale" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_item"
  ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_item"
  ADD FOREIGN KEY ("batch_id") REFERENCES "batch" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_item"
  ADD FOREIGN KEY ("last_sync_id") REFERENCES "erp_sync" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement"
  ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement"
  ADD FOREIGN KEY ("batch_id") REFERENCES "batch" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement"
  ADD FOREIGN KEY ("sale_item_id") REFERENCES "sale_item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_movement"
  ADD FOREIGN KEY ("last_sync_id") REFERENCES "erp_sync" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_analysis"
  ADD FOREIGN KEY ("ml_execution_id") REFERENCES "ml_execution" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_analysis"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_analysis"
  ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_analysis"
  ADD FOREIGN KEY ("flow_type_id") REFERENCES "flow_type_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion"
  ADD FOREIGN KEY ("product_analysis_id") REFERENCES "product_analysis" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion"
  ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion"
  ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion"
  ADD FOREIGN KEY ("created_by_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion_triage"
  ADD FOREIGN KEY ("suggestion_id") REFERENCES "suggestion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion_triage"
  ADD FOREIGN KEY ("employee_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion_decision"
  ADD FOREIGN KEY ("suggestion_id") REFERENCES "suggestion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion_decision"
  ADD FOREIGN KEY ("manager_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion_log"
  ADD FOREIGN KEY ("suggestion_id") REFERENCES "suggestion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suggestion_log"
  ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_event"
  ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

INSERT INTO "flow_type_catalog" ("code", "description") VALUES
  ('HIGH', 'Stockout or replenishment risk'),
  ('MEDIUM', 'Stock is adequate for current demand'),
  ('LOW', 'Expiration or excess stock risk')
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "role" ("code", "name") VALUES
  ('ADMIN', 'ADMIN'),
  ('GERENTE', 'GERENTE'),
  ('GERENTE_REGIONAL', 'GERENTE_REGIONAL'),
  ('FUNCIONARIO', 'FUNCIONARIO')
ON CONFLICT ("code") DO NOTHING;
