-- Upgrade the schema shipped in quistock-updated.sql to support persisted ERP snapshots
-- and rule-based analysis before ML and NoSQL-backed actor resolution are integrated.

ALTER TABLE "product"
  ALTER COLUMN "sale_price" DROP NOT NULL;

ALTER TABLE "product"
  ALTER COLUMN "sku" TYPE VARCHAR(150);

ALTER TABLE "batch"
  DROP CONSTRAINT IF EXISTS "batch_batch_number_key";

ALTER TABLE "batch"
  ALTER COLUMN "expiration_date" DROP NOT NULL;

ALTER TABLE "batch"
  ALTER COLUMN "batch_number" TYPE VARCHAR(150);

ALTER TABLE "batch"
  ADD COLUMN IF NOT EXISTS "entry_date" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "sale_price" NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS "unit_cost" NUMERIC(12,2);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_batch_prices'
      AND conrelid = 'batch'::regclass
  ) THEN
    ALTER TABLE "batch"
      ADD CONSTRAINT "chk_batch_prices"
      CHECK (
        (sale_price IS NULL OR sale_price >= 0)
        AND (unit_cost IS NULL OR unit_cost >= 0)
      );
  END IF;
END;
$$;

ALTER TABLE "store"
  ALTER COLUMN "region_id" DROP NOT NULL,
  ALTER COLUMN "created_by_id" DROP NOT NULL;

ALTER TABLE "product_analysis"
  ALTER COLUMN "ml_execution_id" DROP NOT NULL;

ALTER TABLE "suggestion_triage"
  ALTER COLUMN "employee_id" DROP NOT NULL;

ALTER TABLE "suggestion_decision"
  ALTER COLUMN "manager_id" DROP NOT NULL;

ALTER TABLE "suggestion"
  DROP CONSTRAINT IF EXISTS "chk_suggestion_origin_creator";

ALTER TABLE "suggestion"
  ADD CONSTRAINT "chk_suggestion_origin_creator"
  CHECK (
    (origin = 'ML' AND created_by_id IS NULL)
    OR origin IN ('EMPLOYEE', 'MANAGER')
  );

CREATE TABLE IF NOT EXISTS "product_store" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" BIGINT NOT NULL REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "store_id" BIGINT NOT NULL REFERENCES "store" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "minimum_stock_quantity" NUMERIC(14,3),
  "supplier_lead_time_days" INT,
  "sales_7d" NUMERIC(14,3) NOT NULL DEFAULT 0,
  "sales_30d" NUMERIC(14,3) NOT NULL DEFAULT 0,
  "sale_price" NUMERIC(12,2),
  "unit_cost" NUMERIC(12,2),
  "last_restock_at" TIMESTAMPTZ,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "last_sync_id" BIGINT REFERENCES "erp_sync" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT "chk_product_store_minimum_stock"
    CHECK (minimum_stock_quantity IS NULL OR minimum_stock_quantity >= 0),
  CONSTRAINT "chk_product_store_lead_time"
    CHECK (supplier_lead_time_days IS NULL OR supplier_lead_time_days >= 0),
  CONSTRAINT "chk_product_store_sales"
    CHECK (sales_7d >= 0 AND sales_30d >= 0),
  CONSTRAINT "chk_product_store_prices"
    CHECK (
      (sale_price IS NULL OR sale_price >= 0)
      AND (unit_cost IS NULL OR unit_cost >= 0)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_product_store_pair"
  ON "product_store" ("product_id", "store_id");

CREATE INDEX IF NOT EXISTS "idx_product_store_store_active"
  ON "product_store" ("store_id", "active");

CREATE INDEX IF NOT EXISTS "idx_batch_product_store_active"
  ON "batch" ("product_id", "store_id", "active");

COMMENT ON COLUMN "batch"."entry_date"
  IS 'Batch entry timestamp provided by the ERP.';

COMMENT ON COLUMN "batch"."unit_cost"
  IS 'Unit acquisition cost provided by the ERP.';

COMMENT ON COLUMN "product_store"."minimum_stock_quantity"
  IS 'ERP minimum stock quantity for this product at this store.';

COMMENT ON COLUMN "product_store"."supplier_lead_time_days"
  IS 'Supplier delivery lead time in days provided by the ERP.';

COMMENT ON COLUMN "product_store"."unit_cost"
  IS 'Unit acquisition cost from the most recent batch at this store.';

COMMENT ON COLUMN "product_store"."last_restock_at"
  IS 'Entry date of the most recently received batch provided by the ERP.';

INSERT INTO "flow_type_catalog" ("code", "description") VALUES
  ('HIGH', 'Stockout or replenishment risk'),
  ('MEDIUM', 'Stock is adequate for current demand'),
  ('LOW', 'Expiration or excess stock risk')
ON CONFLICT ("code") DO NOTHING;
