name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 26
          cache: gradle

      - name: 'DEBUG: Show Java version'
        run: java -version

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

  lint-and-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 26
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Spotless Check
        run: ./gradlew spotlessCheck

      - name: Checkstyle Check
        run: ./gradlew checkstyleMain

  tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 26
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Check test coverage
        run: ./gradlew jacocoTestCoverageVerification
