name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - qa
  workflow_dispatch:

env:
  JAVA_VERSION: "26"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

  lint-and-code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Spotless Check
        run: ./gradlew spotlessCheck

      - name: Checkstyle Check
        run: ./gradlew checkstyleMain

  tests-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Check test coverage
        run: ./gradlew jacocoTestCoverageVerification