name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  JAVA_VERSION: "26"

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: ./.github/setup-environment

      - name: Build
        run: ./gradlew build

  lint-and-code-style:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: ./.github/setup-environment

      - name: Spotless Check
        run: ./gradlew spotlessCheck

      - name: Checkstyle Check
        run: ./gradlew checkstyleMain

  tests-and-coverage:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: ./.github/setup-environment

      - name: Run tests
        run: ./gradlew test

      - name: Check test coverage
        run: ./gradlew jacocoTestCoverageVerification